### ISSUE TITLE
Crash on Y press

### ISSUE THREAD

**Issue by heyjoeway** [VeritasDL/SADXCHAOS#7]
Using nothing but Chaos Edition and the Input Mod, pressing Y causes the game to crash, even in menus. The only reference to the Y button I could find is here, though the block is empty?
https://github.com/VeritasDL/SADXCHAOS/blob/1cbc76a759a4474baf583c8fecce8b0c32e2a581/SADXCHAOS/Chaos.cpp#L1065
No clue what's going on. I'm wondering if there's something more specific to my setup wrong since it's so easy to trigger.

**Comment by heyjoeway** [comment]
...oh.
https://github.com/VeritasDL/SADXCHAOS/blob/3c65046f440b2cec6c4c1c28b826fab718931a6c/SADXCHAOS/Chaos.cpp#L2551

**Comment by heyjoeway** [comment]
Eeeyup. Closing since it's not a problem in the latest commit (but it is in the current release).

**Comment by VeritasDL** [comment]
wow thats weird, ill have to test the release and make sure it doesnt crash, if it does then ill push a update,
was the crash something that happend when you were using the Release build? or was it a build you built with VS?

**Comment by VeritasDL** [comment]
Pushed a update anyway.
